name: Push Supabase Edge Functions

on:
  push:
    branches:
      - "main"

jobs:
  push-edge-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo so CI can access the source files
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: supabase/setup-cli@v1

      - name: Authenticate Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link to Supabase Project
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: supabase link --project-ref "$SUPABASE_PROJECT_ID"

      - name: Push Edge Functions
        run: |
          supabase functions deploy create-certificate --project-ref "$SUPABASE_PROJECT_ID"
          supabase functions deploy sign-document --project-ref "$SUPABASE_PROJECT_ID"
          supabase functions deploy verify-document --no-verify-jwt --project-ref "$SUPABASE_PROJECT_ID"
